# Generated by Django 6.0.2 on 2026-02-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desktop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available for purchase'), ('SOLD', 'Sold'), ('RESTOCKING', 'Restocking soon')], default='SOLD', max_length=20)),
                ('issues', models.CharField(default='None', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available for purchase'), ('SOLD', 'Sold'), ('RESTOCKING', 'Restocking soon')], default='SOLD', max_length=20)),
                ('issues', models.CharField(default='None', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available for purchase'), ('SOLD', 'Sold'), ('RESTOCKING', 'Restocking soon')], default='SOLD', max_length=20)),
                ('issues', models.CharField(default='None', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
